application: jonesir-mobile-tu-bs
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: willkommen.application
- url: /fakultaeten/.*
  script: fakultaeten.application